### ISSUE TITLE
提个优化建议，文字变成可复制状态，如图

### ISSUE THREAD

**Issue by hcllmsx** [Dreamefwy/CG-Tools#1]
![请求改为可复制状态](https://user-images.githubusercontent.com/63240764/162648376-0dc296e3-ab68-4533-b3bb-0699469465d9.png)
教程中不是要设置这些选项，然后文字要自己手打么，哈哈，伸手党表示，能不能把这个文字弄成可复制状态。

**Comment by hcllmsx** [comment]
![关于置顶按钮](https://user-images.githubusercontent.com/63240764/162648813-2e4e6b00-01b4-49dc-9f55-5440fa518f20.png)
另外这个置顶设置按钮，反正只有一个功能就是置顶，我觉得用不着做成这样的二级菜单形式的。就直接弄成一个按钮【置顶】，点一下之后，文字变成【取消置顶】。或者像像下面的一样，前面弄个选择框，打勾就是置顶模式，取消勾选就是不置顶模式。
嘻嘻嘻，望作者采纳。

**Comment by Dreamefwy** [comment]
一键复制功能已经开发完毕，将会在下一个版本中出现，下个版本将会在我下一个教程视频中介绍及同步放出



發自我的iPhone


------------------ 原始邮件 ------------------
寄件人： 火车啦啦 ***@***.***&gt;
发送时间: 2022年4月11日 09:07
收件人： Dreamefwy/CG-Tools ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主旨： Re: [Dreamefwy/CG-Tools] 提个优化建议，文字变成可复制状态，如图 (Issue #1)





 

 另外这个置顶设置按钮，反正只有一个功能就是置顶，我觉得用不着做成这样的二级菜单形式的。就直接弄成一个按钮【置顶】，点一下之后，文字变成【取消置顶】。或者像像下面的一样，前面弄个选择框，打勾就是置顶模式，取消勾选就是不置顶模式。
 嘻嘻嘻，望作者采纳。
